const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../secret-run.js'),B=require('../badge-system.js'),{PHASE:P}=R;
function hit(run,key='normal',now=1){return R.reduce(run,{type:'CAPTURE',key,now});}
function charged(){let r=R.create();for(let i=1;i<=20;i++)r=hit(r,'normal',i*100);return r;}
function called(){return R.reduce(charged(),{type:'CALL',now:2100});}
test('Moon gauge requires 20 and trap hit removes five charge',()=>{let r=R.create();for(let i=1;i<=19;i++)r=hit(r,'normal',i*100);assert.equal(r.phase,P.NORMAL);assert.equal(r.gauge,19);r=hit(r,'normal',2000);assert.equal(r.phase,P.READY);assert.equal(r.gauge,20);r=hit(r,'annyongi',2010);assert.equal(r.phase,P.NORMAL);assert.equal(r.gauge,15);for(let i=0;i<3;i++)r=R.reduce(r,{type:'DODGE',now:2020+i});assert.equal(r.gauge,16);assert.equal(R.GAUGE_MAX,20);});
test('Eclipse and Flight pause the 30s clock and first return hardens combo timing',()=>{let r=called();r=R.advance(r,2800);const remaining=r.remainingMs;assert.equal(r.phase,P.ECLIPSE);r=R.advance(r,7800);assert.equal(r.phase,P.FLIGHT);assert.equal(r.remainingMs,remaining);r=R.advance(r,12800);assert.equal(r.phase,P.NORMAL);assert.equal(r.remainingMs,remaining);assert.equal(r.completedCalls,1);assert.equal(R.comboWindow(r),1950);});
test('Two calls extend wall-clock while active play remains 30 seconds',()=>{let r=called();r=R.advance(r,12800);for(let i=1;i<=20;i++)r=hit(r,'normal',12800+i*100);r=R.reduce(r,{type:'CALL',now:14900});r=R.advance(r,25600);assert.equal(r.completedCalls,2);r=R.advance(r,70000);const result=R.result(r);assert.ok(result.durationMs>40000);assert.equal(result.activeDurationMs,30000);});
test('Eclipse and Flight scoring remains exact',()=>{let r=R.advance(called(),2800);r=hit(r,'gold',4000);assert.equal(r.eclipseScore,2);r=R.advance(r,7800);const before=R.total(r);r=hit(r,'indeoki',8000);assert.equal(R.total(r)-before,10);assert.equal(r.gauge,0);});
test('Late call cannot outrun remaining active clock',()=>{let r=charged();r=R.advance(r,29999);r=R.reduce(r,{type:'CALL',now:29999});r=R.advance(r,31000);assert.equal(r.phase,P.RESULT);assert.equal(R.result(r).completed,false);});
test('RC academic grades require stronger performance and two calls for A',()=>{assert.equal(R.contract({completed:false,totalScore:999,rareCaptures:99,eclipseCaptures:99,flightCaptures:99,completedCalls:2}).rank,'F');for(const rank of R.RANKS.slice(1)){const v={completed:true,totalScore:rank.score,rareCaptures:rank.rare,eclipseCaptures:rank.eclipse,flightCaptures:rank.flight,completedCalls:rank.calls};assert.equal(R.contract(v).rank,rank.rank);}assert.equal(R.contract({completed:true,totalScore:349,rareCaptures:99,eclipseCaptures:99,flightCaptures:99,completedCalls:2}).rank,'B+');});
test('Ascension ground score uses cumulative x1.2 then x1.5 bonuses',()=>{let r=called();r=R.advance(r,12800);assert.equal(r.completedCalls,1);const before1=R.total(r);for(let i=1;i<=5;i++)r=hit(r,'normal',12800+i*100);assert.equal(r.tier1GroundAward,5);assert.equal(r.ascensionBonus,1);assert.equal(R.total(r)-before1,6);for(let i=6;i<=20;i++)r=hit(r,'normal',12800+i*100);r=R.reduce(r,{type:'CALL',now:14900});r=R.advance(r,25600);assert.equal(r.completedCalls,2);const bonusBefore=r.ascensionBonus,totalBefore=R.total(r);r=hit(r,'normal',25700);r=hit(r,'normal',25800);assert.equal(r.tier2GroundAward,2);assert.equal(r.ascensionBonus-bonusBefore,1);assert.equal(R.total(r)-totalBefore,3);assert.deepEqual(R.ASCENSION_BONUS,{1:.2,2:.5});});
test('Unified badge tiers use score plus stars',()=>{assert.equal(B.general(749,12).code,'campus_explorer');assert.equal(B.general(750,10).code,'campus_master');assert.equal(B.general(1000,12).code,'inha_king');assert.equal(B.grade('A+').label,'비룡의 눈');});
test('Inha Duck S1 podium badges are frozen event badges',()=>{
  assert.equal(B.EVENT.length,4);
  assert.equal(B.eventByCode('inha_duck_s1_gold').label,'인하오리 S1 우승');
  assert.equal(B.eventByCode('inha_duck_s1_silver').icon,'🥈');
  assert.equal(B.eventByCode('inha_duck_s1_bronze').icon,'🥉');
  assert.equal(B.eventByCode('inha_duck_s1_top10').label,'인하오리 S1 TOP 10');
  assert.equal(B.eventByCode('unknown'),null);
});
test('History uses v5',()=>{assert.deepEqual(R.normalizeHistory(),{version:5,plays:0,bestScore:0,bestContract:null});let h=R.record(undefined,{totalScore:400,contract:{rank:'A+'}});h=R.record(h,{totalScore:90,contract:{rank:'D0'}});assert.equal(h.bestContract,'A+');});
test('Reducers do not mutate input',()=>{const r=R.create(),copy=structuredClone(r);hit(r,'gold',10);assert.deepEqual(r,copy);});
