import test from 'node:test';
import assert from 'node:assert/strict';
import { createToastQueue } from '../src/events/zombie-university-2026/event-ui.js';
import { createCore15FunnelTelemetry } from '../src/core15-funnel-telemetry.js';
function toastHarness(){const timers=[];const element={hidden:true,textContent:'',isConnected:true,parentElement:null,ownerDocument:{visibilityState:'visible',defaultView:{getComputedStyle:()=>({display:'block',visibility:'visible',opacity:'1'})}},getClientRects:()=>[{width:200,height:80}]};const queue=createToastQueue({element,setTimer:fn=>(timers.push(fn),fn),clearTimer:fn=>{const i=timers.indexOf(fn);if(i>=0)timers.splice(i,1);},now:()=>0});return {queue,element,timers};}
test('receipt toast handle reports only its own actually visible message',()=>{const {queue,element,timers}=toastHarness();const first=queue.say('other',20);const receipt=queue.say('receipt',20);assert.ok(receipt,'queue returns presentation receipt');assert.equal(receipt.isVisible(),false);timers.shift()();timers.shift()();assert.equal(receipt.isVisible(),true);element.ownerDocument.visibilityState='hidden';assert.equal(receipt.isVisible(),false);assert.equal(first.isVisible(),false);});
test('stale queued and currently visible receipts are invalidated on account switch',()=>{const {queue,element,timers}=toastHarness();let current=true;const a=queue.say('A reward',20,null,()=>current);queue.say('A queued',20,null,()=>current);queue.say('B ordinary',20);assert.ok(a);current=false;assert.equal(typeof queue.prune,'function');queue.prune();assert.equal(a.isVisible(),false);while(timers.length)timers.shift()();assert.notEqual(element.textContent,'A queued');});
test('old account telemetry cannot complete after delayed confirmation',async()=>{let current=true,release;const events=[];const telemetry=createCore15FunnelTelemetry({storage:null,isCurrent:()=>current,eventIdFactory:()=> '00000000-0000-4000-8000-000000000001',track:async(event,_surface,_target,{eventId})=>{events.push(event);await new Promise(resolve=>release=resolve);return eventId;}});telemetry.firstReward();current=false;release();await Promise.resolve();await Promise.resolve();assert.deepEqual(telemetry.status().seen,[]);assert.equal(telemetry.rewardSeen(),false);assert.deepEqual(events,['first_reward']);});
test('an unseen receipt waits through a background tab instead of expiring',()=>{const {queue,element,timers}=toastHarness();element.ownerDocument.visibilityState='hidden';const ticket=queue.say('receipt',4500,null,()=>true,()=>true);assert.ok(ticket);assert.equal(ticket.isVisible(),false);assert.equal(timers.length,0);element.ownerDocument.visibilityState='visible';queue.prune();assert.equal(ticket.isVisible(),true);assert.equal(timers.length,1);element.ownerDocument.visibilityState='hidden';timers.shift()();assert.equal(ticket.isVisible(),false);element.ownerDocument.visibilityState='visible';queue.prune();assert.equal(ticket.isVisible(),true);assert.equal(timers.length,1);});
test('receipt presentation can wait for leaving the lobby without blocking cancellation',()=>{const {queue,timers}=toastHarness();let canPresent=false,current=true;const ticket=queue.say('receipt',4500,null,()=>current,()=>canPresent);assert.equal(ticket.isVisible(),false);assert.equal(timers.length,0);canPresent=true;queue.prune();assert.equal(ticket.isVisible(),true);canPresent=false;queue.prune();assert.equal(ticket.isVisible(),false);current=false;canPresent=true;queue.prune();assert.equal(ticket.isVisible(),false);assert.equal(queue.length,0);});
